### PR TITLE
Use create-react-context

### PR DESCRIPTION
**Pull request by pedronauck**
Add `create-react-context` in order to guarantee compatibility with old versions of React

### CODE REVIEW

**Comment by renatorib** [comment]
I think this is extremely important. I had problems trying to use a lib that had copy-write as dependency, in my application with react 15.

**Comment by aweary** [comment]
Hmm, I didn't intend to support older versions of React, but I didn't consider transitive dependencies.

**Comment by pedronauck** [comment]
We're using `react-copy-write` on docz and now has a bunch of projects with this bug, if you won't consider support to use `create-react-context` unfortunately I gonna have to change and use another state management, it's a really bad thing since I really like your package 😕

**Comment by aweary** [comment]
Ok, Im happy to support this in that case. I'll get out a release with this fix soon!

**Comment by aweary** [comment]
I've published 0.8.0 with this change. Thanks for bringing this up @pedronauck!

**Pull request merged**
